apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
spec:
  # The service initially targets the BLUE deployment.
  selector:
    app: myapp
    color: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Use LoadBalancer to expose it easily via Minikube
